[common]
base_url = "http://localhost"
available_llm_providers = [
    "openai",
    "groq",
    "anthropic",
    "ollama",
    "google-gla",
]
GROQ_API_KEY = ""
OPENAI_API_KEY = ""
ANTHROPIC_API_KEY = ""
OLLAMA_API_KEY = ""
GOOGLE_API_KEY = ""
mlflow_port = 5000

[app]
port = 3000
backend_port = 8000
text_to_sql_model = "google-gla:gemini-2.5-flash"
company_summary_model = "groq:openai/gpt-oss-120b"
company_summary_qa_model = "google-gla:gemini-2.5-flash"

[stockdb]
port = 8080
data_base_path = '/shared/assets/stockdb' # Use Docker mount target path
download_batch_size = 80
